version: '3.1'

services:

  php:
    build: ./builds/php
    restart: unless-stopped
    volumes:
      - ./:/var/www

  nginx:
    build: ./builds/nginx
    restart: unless-stopped
    ports:
      - 8082:80
    links:
      - php
    volumes:
      - ./:/var/www
